services:
  - type: web
    name: ok-strapi-web
    env: node
    plan: free
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    envVars:
      - key: NODE_VERSION
        value: ~16.17.0
      - key: NODE_ENV
        value: production
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_ACCESS_SECRET
        sync: false
      - key: AWS_REGION
        sync: false
      - key: AWS_BUCKET_NAME
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: ok-strapi-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: APP_KEYS
        generateValue: true

databases:
  - name: ok-strapi-db
    plan: free
